# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

APP_NAME = "BeatMaster"
SCHEME = "BeatMaster"

KEYCHAIN_NAME = ENV["KEYCHAIN_NAME"]
KEYCHAIN_PASSWORD = ENV["KEYCHAIN_PASSWORD"]
KEYCHAIN_PASSWORD_DB =  ENV["KEYCHAIN_PASSWORD_DB"]
#require 'spaceship'
#Spaceship::ConnectAPI::App.const_set('ESSENTIAL_INCLUDES', 'appStoreVersions')
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
   # ✅ 인증서를 키체인에 저장
  desc "Save To Keychain"
  lane :set_keychain do |options|
    sh"tuist signing decrypt"
    create_keychain(
      name: "#{KEYCHAIN_NAME}",
      password: "#{KEYCHAIN_PASSWORD}",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true
    )

    import_certificate(
      certificate_path: "Tuist/Signing/release.cer",
      keychain_name: "#{KEYCHAIN_NAME}",
      keychain_password: "#{KEYCHAIN_PASSWORD}"
    )

    import_certificate(
      certificate_path: "Tuist/Signing/release.p12",
      keychain_name: "#{KEYCHAIN_NAME}",
      keychain_password: "#{KEYCHAIN_PASSWORD}"
    )
  end

desc "Install Profiles and Build My App"
  lane :build_ipa do
    clear_derived_data

     sh"tuist signing decrypt"

   # get_certificates(
   # filename: "release.cer",
   # output_path: "./fastlane/Signing/")
  # get_provisioning_profile(
   # app_identifier: "com.Haejoo.BeatMaster",
   # filename: "#{APP_NAME}.Release.mobileprovision",
   # output_path: "./fastlane/Signing/")

  unlock_keychain(
    path: "/Users/suhwonji/Library/Keychains/BeatMaster-db",
    password: "$KEYCHAIN_PASSWORD_DB"
  )
  
  gym(
 configuration: "Release",
     workspace: "BeatMaster.xcworkspace",
     scheme: "BeatMaster",
    silent: true,
   xcargs: "SWIFT_VERSION=5.9",
   clean: true,
  output_directory: "./fastlane/output/",
  output_name: "BeatMaster.ipa",
 export_method: "app-store",
#     signingStyle: "manual",
     export_options: {
        uploadBitcode: false,
        provisioningProfiles: {
       "com.Haejoo.BeatMaster" => "BeatMaster",
      "com.Haejoo.BeatMaster.Demo" => "BeatMasterDemo"
           }
        }
    )
 
   end

 # ✅ 테스트 플라이트 업로드
  desc "Push to TestFlight"
  lane :QA do |options|
    install_provisioning_profile(path: "Tuist/Signing/#{APP_NAME}.Release.mobileprovision")
   clear_derived_data
   # ✅ 빌드
    build_app(
      workspace: "#{APP_NAME}.xcworkspace",
      scheme: "#{SCHEME}",
    silent: true,
    clean: true,
    output_directory: "./fastlane/output/",
    output_name: "BeatMaster.ipa",
      export_method: "app-store",
      export_options: {
      #signingStyle: "automatic",
          uploadBitcode: false,
          provisioningProfiles: {
            "com.Haejoo.BeatMaster" => "BeatMaster",
             "com.Haejoo.BeatMaster.Demo" => "BeatMasterDemo"
             }
        }
    )

 end
end
