name: uploadApp2

on:
  push:
    branches: [ "Dev" ]

jobs:
  build:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v2

      - run: fastlane QA
        working-directory: ./BeatMaster
        env:
          # KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
          # KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
